import { createServerClient } from "@supabase/ssr";
import type { Metadata } from "next";
import Link from "next/link";

/**
 * Public sample briefing page — no auth required.
 *
 * Shows a real, daily-generated briefing on "Artificial Intelligence"
 * produced by the exact same Gemini + grounding pipeline that powers
 * user briefings. Updated daily by the cron job.
 *
 * Purpose: zero-friction product demo, shareable URL, SEO-indexable
 * fresh content.
 */

// Revalidate every 60 seconds so new cron-generated briefings appear quickly
export const revalidate = 60;

const SAMPLE_USER_ID = "0a1ee72f-2d65-4062-8c0b-db92305cae1d";

export const metadata: Metadata = {
  title: "Today's AI Briefing",
  description:
    "A daily AI-synthesized intelligence briefing on Artificial Intelligence. See what Brain Brief delivers to your inbox every morning — sourced, cited, and ready in 5 minutes.",
  openGraph: {
    title: "Today's AI Briefing — Brain Brief",
    description:
      "A daily AI-synthesized intelligence briefing on Artificial Intelligence. See what Brain Brief delivers every morning.",
    url: "https://www.brainbrief.app/sample",
    siteName: "Brain Brief",
    type: "article",
    images: [
      {
        url: "https://www.brainbrief.app/og-image.png",
        width: 1200,
        height: 630,
        alt: "Brain Brief — Your AI Morning Briefing",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Today's AI Briefing — Brain Brief",
    description:
      "A daily AI-synthesized intelligence briefing on Artificial Intelligence.",
    images: ["https://www.brainbrief.app/og-image.png"],
  },
};

export default async function SamplePage() {
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      cookies: {
        getAll() {
          return [];
        },
        setAll() {},
      },
    }
  );

  // Fetch the latest sample briefing
  const { data: briefing } = await supabase
    .from("briefings")
    .select("content_html, topics_covered, created_at, grounded, subject_line")
    .eq("user_id", SAMPLE_USER_ID)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "short",
    day: "numeric",
  });

  // Article JSON-LD for Google Discover — fresh daily content on AI
  const sampleJsonLd = briefing
    ? {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: briefing.subject_line || "Today's AI Intelligence Briefing",
        description:
          "A daily AI-synthesized intelligence briefing on Artificial Intelligence, generated by Brain Brief.",
        image: "https://www.brainbrief.app/og-image.png",
        datePublished: briefing.created_at.split("T")[0],
        dateModified: briefing.created_at.split("T")[0],
        author: {
          "@type": "Organization",
          name: "Brain Brief",
          url: "https://www.brainbrief.app",
        },
        publisher: {
          "@type": "Organization",
          name: "Brain Brief",
          logo: {
            "@type": "ImageObject",
            url: "https://www.brainbrief.app/logo-512.png",
          },
        },
        mainEntityOfPage: {
          "@type": "WebPage",
          "@id": "https://www.brainbrief.app/sample",
        },
        about: {
          "@type": "Thing",
          name: "Artificial Intelligence",
        },
      }
    : null;

  return (
    <div className="min-h-screen bg-background">
      {sampleJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(sampleJsonLd) }}
        />
      )}
      {/* Header */}
      <header className="border-b border-border bg-card">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link
            href="/"
            className="font-sans text-lg font-bold text-primary tracking-tight"
          >
            Brain Brief
          </Link>
          <Link
            href="/signup?utm_source=sample&utm_medium=organic"
            className="inline-flex items-center px-4 py-2 bg-primary text-primary-foreground text-sm font-semibold rounded-lg hover:opacity-90 transition-opacity"
          >
            Get your own briefing
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        {/* Page intro */}
        <div className="mb-8">
          <p className="text-sm font-bold text-accent uppercase tracking-wider mb-2">
            Sample Briefing
          </p>
          <h1 className="font-serif text-3xl sm:text-4xl font-bold text-primary mb-3">
            Today&apos;s AI Intelligence Briefing
          </h1>
          <p className="text-muted-foreground text-lg leading-relaxed">
            This is a real briefing generated by Brain Brief this morning — the
            same quality delivered to subscribers every day.
          </p>
        </div>

        {briefing ? (
          <>
            {/* Briefing card — identical to dashboard rendering */}
            <div className="bg-card shadow-xl shadow-slate-200/50 border border-border rounded-2xl overflow-hidden">
              <div className="bg-muted border-b border-border px-6 sm:px-8 py-6 flex items-center justify-between">
                <h2 className="font-serif text-xl font-bold text-primary">
                  Today&apos;s Briefing
                </h2>
                <span className="text-sm font-medium text-muted-foreground">
                  {new Date(briefing.created_at).toLocaleDateString("en-US", {
                    weekday: "long",
                    year: "numeric",
                    month: "short",
                    day: "numeric",
                  })}
                </span>
              </div>

              <div className="p-6 sm:p-8">
                {briefing.topics_covered &&
                  Array.isArray(briefing.topics_covered) && (
                    <div className="flex flex-wrap gap-2 mb-8">
                      {briefing.topics_covered.map((topic: string) => (
                        <span
                          key={topic}
                          className="inline-flex items-center rounded-md bg-muted px-2.5 py-1 text-xs font-bold text-primary border border-border uppercase tracking-wider"
                        >
                          {topic}
                        </span>
                      ))}
                    </div>
                  )}
                <div
                  className="prose prose-slate max-w-none text-base text-muted-foreground leading-relaxed break-words overflow-hidden"
                  dangerouslySetInnerHTML={{
                    __html: briefing.content_html,
                  }}
                />
              </div>
            </div>

            {/* CTA section */}
            <div className="mt-10 bg-card border border-border rounded-2xl p-8 sm:p-10 text-center">
              <h2 className="font-serif text-2xl font-bold text-primary mb-3">
                This is one topic.
              </h2>
              <p className="text-muted-foreground text-lg mb-6 max-w-lg mx-auto leading-relaxed">
                Imagine getting this for{" "}
                <span className="font-semibold text-primary">
                  everything you care about
                </span>{" "}
                — every morning, in your inbox, fully sourced and ready in 5
                minutes.
              </p>
              <Link
                href="/signup?utm_source=sample&utm_medium=organic&utm_campaign=sample_cta"
                className="inline-flex items-center px-8 py-4 bg-primary text-primary-foreground text-base font-bold rounded-xl hover:opacity-90 transition-opacity shadow-md shadow-primary/20"
              >
                Start your free trial &rarr;
              </Link>
              <p className="mt-4 text-sm text-muted-foreground">
                7-day free trial &middot; No credit card required
              </p>
            </div>
          </>
        ) : (
          /* No briefing yet — first-day state */
          <div className="bg-card border border-border rounded-2xl p-12 text-center">
            <div className="max-w-md mx-auto">
              <h2 className="font-serif text-2xl font-bold text-primary mb-3">
                Today&apos;s briefing is being prepared
              </h2>
              <p className="text-muted-foreground text-base mb-6">
                Our AI is generating this morning&apos;s intelligence briefing.
                Check back shortly — it&apos;s usually ready by{" "}
                <span className="font-medium">7:00 AM ET</span>.
              </p>
              <p className="text-sm text-muted-foreground mb-8">
                {today}
              </p>
              <Link
                href="/signup?utm_source=sample&utm_medium=organic&utm_campaign=sample_cta"
                className="inline-flex items-center px-6 py-3 bg-primary text-primary-foreground text-sm font-bold rounded-xl hover:opacity-90 transition-opacity"
              >
                Get notified when it&apos;s ready &rarr;
              </Link>
            </div>
          </div>
        )}

        {/* How it works mini-section */}
        <div className="mt-12 border-t border-border pt-10">
          <div className="grid sm:grid-cols-3 gap-6 text-center">
            <div>
              <div className="w-10 h-10 rounded-full bg-muted border border-border flex items-center justify-center mx-auto mb-3">
                <span className="font-serif font-bold text-accent text-sm">
                  1
                </span>
              </div>
              <h3 className="font-semibold text-primary text-sm mb-1">
                Pick your topics
              </h3>
              <p className="text-muted-foreground text-sm">
                AI, climate, markets, policy — anything you follow
              </p>
            </div>
            <div>
              <div className="w-10 h-10 rounded-full bg-muted border border-border flex items-center justify-center mx-auto mb-3">
                <span className="font-serif font-bold text-accent text-sm">
                  2
                </span>
              </div>
              <h3 className="font-semibold text-primary text-sm mb-1">
                We research overnight
              </h3>
              <p className="text-muted-foreground text-sm">
                AI synthesizes thousands of sources while you sleep
              </p>
            </div>
            <div>
              <div className="w-10 h-10 rounded-full bg-muted border border-border flex items-center justify-center mx-auto mb-3">
                <span className="font-serif font-bold text-accent text-sm">
                  3
                </span>
              </div>
              <h3 className="font-semibold text-primary text-sm mb-1">
                Read in 5 minutes
              </h3>
              <p className="text-muted-foreground text-sm">
                Cited, structured, no fluff — in your inbox every morning
              </p>
            </div>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-12 py-6">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} Brain Brief</p>
          <div className="flex gap-4">
            <Link href="/blog" className="hover:text-primary transition-colors">
              Blog
            </Link>
            <Link
              href="/terms"
              className="hover:text-primary transition-colors"
            >
              Terms
            </Link>
            <Link
              href="/privacy"
              className="hover:text-primary transition-colors"
            >
              Privacy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
